esphome:
  name: rover

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino
    #type: esp-idf
    # sdkconfig_options:
    #   CONFIG_LOG_MAXIMUM_LEVEL_DEBUG: y

# Enable logging
logger:
  # level: VERBOSE
  # logs:
  #   camera: VERBOSE
  #   wifi: INFO

ota:
  - platform: esphome
    password: ""

wifi:
  domain: .home
  power_save_mode: none
  output_power: 18dB
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      hidden: !secret wifi_hidden
      bssid: !secret wifi_bssid
  # # Alternatively operate in AP mode
  # ap:
  #   ssid: !secret ap_mode_ssid
  #   password: !secret ap_mode_password

external_components:
  - source:
      type: local
      path: components

rover_web_server:
  port: 80
  version: 2
  include_internal: true
# esp32_camera_web_server:
#   # - port: 8080
#   #   mode: stream
#   - port: 8081
#     mode: snapshot


# External components

fan:
  - platform: hbridge
    id: motor_left
    pin_a: motor_left_1_pwm
    pin_b: motor_left_2_pwm
  - platform: hbridge
    id: motor_right
    pin_a: motor_right_1_pwm
    pin_b: motor_right_2_pwm

output:
  - platform: ledc
    id: motor_left_1_pwm
    pin: GPIO32
    frequency: 1000Hz
    inverted: false
  - platform: ledc
    id: motor_left_2_pwm
    pin: GPIO33
    frequency: 1000Hz
    inverted: false
  - platform: ledc
    id: motor_right_1_pwm
    pin: GPIO0
    frequency: 1000Hz
    inverted: false
  - platform: ledc
    id: motor_right_2_pwm
    pin: GPIO15
    frequency: 1000Hz
    inverted: false

  - platform: ledc
    id: servo_1_pwm
    pin: GPIO12
    frequency: 1000Hz
    inverted: false
  - platform: ledc
    id: servo_2_pwm
    pin: GPIO14
    frequency: 1000Hz
    inverted: false

switch:
  - platform: gpio
    name: "Test LED"
    pin: GPIO2
esp32_camera:
  name: Rover Cam
  external_clock:
    pin: GPIO21
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO4, GPIO5, GPIO18, GPIO19, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  resolution: 1600x1200
  # jpeg_quality: 10
